apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: flyte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: python:3.9-slim
        command: ["/bin/sh", "-c", "pip install mlflow && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: storage
          mountPath: /mlruns
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: flyte
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: flyte
spec:
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30050
  type: NodePort
