apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: ml-train-distributed
  namespace: flyte
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: pytorch
            image: eyesoncloud/ml-train:v1
            command: ["python", "src/orchestration/distributed.py"]
            env:
              - name: MLFLOW_TRACKING_URI
                value: "http://192.168.100.11:30050"
              - name: MASTER_ADDR
                value: "192.168.100.11"
              - name: MASTER_PORT
                value: "29500"
              - name: WORLD_SIZE
                value: "2"
              - name: RANK
                value: "0"
            resources:
              limits:
                cpu: "2"
              requests:
                cpu: "1"
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: pytorch
            image: eyesoncloud/ml-train:v1
            command: ["python", "src/orchestration/distributed.py"]
            env:
              - name: MLFLOW_TRACKING_URI
                value: "http://192.168.100.11:30050"
              - name: MASTER_ADDR
                value: "ml-train-distributed-master-0"
              - name: MASTER_PORT
                value: "29500"
              - name: WORLD_SIZE
                value: "2"
              - name: RANK
                value: "1"
            resources:
              limits:
                cpu: "2"
              requests:
                cpu: "1"
